# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cache
version:      1.83
version_from: Cache.pm
installdirs:  site
requires:
    Parse::RecDescent:             1.8
    Spreadsheet::WriteExcel:       0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
